[service]
name = "delegator"
version = "1.0.0"

[http]
port = 8888
read_timeout = 3600
write_timeout = 3600

[storage]
    [storage.database]
    host = "postgres"
    port = 5432
    username = "delegator"
    database = "delegator_local"
    password = "password"

[logging]
level = "info"
format = "json"