// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockHandler
func (_mock *MockHandler) Run(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockHandler_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandler_Expecter) Run(ctx interface{}) *MockHandler_Run_Call {
	return &MockHandler_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockHandler_Run_Call) Run(run func(ctx context.Context)) *MockHandler_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Run_Call) Return(err error) *MockHandler_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Run_Call) RunAndReturn(run func(ctx context.Context) error) *MockHandler_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockHandler
func (_mock *MockHandler) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHandler_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandler_Expecter) Shutdown(ctx interface{}) *MockHandler_Shutdown_Call {
	return &MockHandler_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockHandler_Shutdown_Call) Run(run func(ctx context.Context)) *MockHandler_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Shutdown_Call) Return(err error) *MockHandler_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockHandler_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
